import '@/styles/global.css'
import '@/styles/style.scss'

export const metadata = {
  title: 'Welcome to demo',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
