@startuml 应用架构

package "Web 端" {
  folder "智能文档" {
    [文档]
    [画板] - [语义组件]
    [模板]
    [工作区] - [面板]
    [工具箱]
    [命令行] - DSL
    [知识可视化]
  }
  folder "智能助理" {
    [问答]
    [生成]
    [提醒]
  }
  folder "第五视界" {
    [知识地图]
    [记忆宫殿]
    [社区管理]
  }
  folder "自我管理" {
    [待办GTD]
    [数据统计]
    [自我认知]
    [改变世界]
  }
}

node "AI大模型" {
  [大模型服务] --> 知识抽取问答界面知识内容生成
  [LangChain] --> ChatGPT、Agent
  [向量数据库]
}

cloud "后台服务" {
  [文档引擎]
  [知识管理]
  [知识抽取]
  [协同服务]
}

database "Neo4j" {
  folder "核心" {
    [语义图谱]
    [概念图谱]
    [常识图谱]
    [开放图谱]
    [专属图谱]
    [文档存储]
  }
}

[画板] --> [文档引擎]
[生成] --> [大模型服务]
[文档引擎] --> [文档存储]

@enduml
